bt_navigator:
  ros__parameters:
    use_sim_time: True

    global_frame: map
    robot_base_frame: base_footprint

    odom_topic: /odom

    transform_tolerance: 0.5

    bt_loop_duration: 10
    default_server_timeout: 20

    navigators: ["navigate_to_pose", "navigate_through_poses"]

    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
   